version: '3.3'
services:
  teobot:
    build: .
    restart: unless-stopped
    user: teobot
    secrets:
      - bot_token
      - google_sheet_credentials
    volumes:
      - ./pickle:/var/google_sheet_pickle
secrets:
  bot_token:
    file: ./bot_token
  google_sheet_credentials:
    file: ./credentials.json
